version: '3.8'

services:
  airflow:
    image: apache/airflow:2.9.0
    environment:
      - _PIP_ADDITIONAL_REQUIREMENTS=duckdb==1.5.2 dbt-core==1.7.0 dbt-duckdb==1.7.0 requests beautifulsoup4 pandas
      # ... rest of your env vars
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__CORE__FERNET_KEY=ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scraper:/opt/airflow/scraper
      - ./dbt_project:/opt/airflow/dbt_project
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        sleep 5 &&
        airflow users create --username admin --password admin --firstname Engy --lastname DE --role Admin --email admin@example.com || true &&
        airflow webserver --port 8080 &
        sleep 10 &&
        airflow scheduler
      "